### PR TITLE
Fix cran

### PR DESCRIPTION
**Pull request by elong0527**
Address open issues in #174, #175, #176 #177

### CODE REVIEW

**Comment by nanxstats** [comment]
The obvious issue here is that `meta_ae_dummy()` does not exist.

**Comment by nanxstats** [comment]
Perhaps I should have been clearer: the name of the function is `meta_ae_example()`, not `meta_ae_dummy()`.

**Comment by fb-elong** [comment]
The CMD check passed now. Please review :)

**Review by nanxstats — APPROVED** [review]
This looks good, thanks for the fixes!

**Pull request merged**
